services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  real-time-chat:
    build: .
    container_name: real-time-chat
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    environment:
      MONGO_URL: mongodb://mongodb:27017/chatapp
      REDIS_URL: redis://redis:6379

volumes:
  mongo-data: